//
// BaseSectionCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct BaseSection: Codable {
    public var userId: Int
    
    public init(userId: Int) { 
        self.userId = userId
    }
    
    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        userId = try container.decode(Int.self, forKey: .userId)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
    }

}
