//
// Member.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public enum MemberRole: String {
    case owner = "owner"
    case admin = "admin"
    case moderator = "moderator"
    case member = "member"
}

public struct Member: Codable {
    public var id: Int?
    public var chat: Int?
    public var user: Int?
    public var isOwner: Bool?
    public var role: String?
    
    public init(id: Int? = nil, chat: Int? = nil, user: Int? = nil, isOwner: Bool? = true, role: String? = MemberRole.owner.rawValue) {
        self.id = id
        self.chat = chat
        self.user = user
        self.isOwner = isOwner
        self.role = role
    }
    
    public enum CodingKeys: String, CodingKey {
        case id
        case chat
        case user
        case isOwner = "is_owner"
        case role
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decodeIfPresent(Int.self, forKey: .id)
        chat = try container.decodeIfPresent(Int.self, forKey: .chat)
        user = try container.decodeIfPresent(Int.self, forKey: .user)
        isOwner = try container.decodeIfPresent(Bool.self, forKey: .isOwner)
        role = try container.decodeIfPresent(String.self, forKey: .role)
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(chat, forKey: .chat)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(isOwner, forKey: .isOwner)
        try container.encodeIfPresent(role, forKey: .role)
    }

}
