//
// Permission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Permission: Codable {
    public var chat: Int?
    public var user: Int
    public var permission: Int
    
    public init(chat: Int? = nil, user: Int, permission: Int) {
        self.chat = chat
        self.user = user
        self.permission = permission
    }
    
    public enum CodingKeys: String, CodingKey {
        case chat
        case user
        case permission
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        chat = try container.decodeIfPresent(Int.self, forKey: .chat)
        user = try container.decode(Int.self, forKey: .user)
        permission = try container.decode(Int.self, forKey: .permission)
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(chat, forKey: .chat)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(permission, forKey: .permission)
    }

}
